[project]
name = 'bitthetix-contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []


[contracts.kycstore]
path = 'contracts/KycStore.clar'
clarity_version = 2
epoch = 2.4

[contracts.arwaproperty]
path = 'contracts/RwaProperty.clar'
clarity_version = 2
epoch = 2.4

[contracts.arwamanager]
path = 'contracts/RwaManager.clar'
clarity_version = 2
epoch = 2.4

[contracts.propertymarketplace]
path = 'contracts/PropertyMarketPlace.clar'
clarity_version = 2
epoch = 2.4

[contracts.rentalcontract]
path = 'contracts/RentalContract.clar'
clarity_version = 2
epoch = 2.4

[contracts.escrowcontract]
path = 'contracts/EscrowContract.clar'
clarity_version = 2
epoch = 2.4

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
