[project]
name = 'bitthetix-contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []


[contracts.kycstore]
path = 'contracts/KycStore.clar'
clarity_version = 2
epoch = 2.4

[contracts.arwaproperty]
path = 'contracts/RwaProperty.clar'
clarity_version = 2
epoch = 2.4

[contracts.arwamanager]
path = 'contracts/RwaManager.clar'
clarity_version = 2
epoch = 2.4

[contracts.propertymarketplace]
path = 'contracts/PropertyMarketPlace.clar'
clarity_version = 2
epoch = 2.4

[contracts.rentalcontract]
path = 'contracts/RentalContract.clar'
clarity_version = 2
epoch = 2.4

[contracts.escrowcontract]
path = 'contracts/EscrowContract.clar'
clarity_version = 2
epoch = 2.4
[contracts.bitthetix]
path = 'contracts/infinitystacks.clar'
clarity_version = 2
epoch = 2.4

[contracts.mock-price-feed]
path = 'contracts/mock-price-feed.clar'
clarity_version = 2
epoch = 2.4


[contracts.sbtc]
path = 'contracts/sBTC/asset.clar'
clarity_version = 2
epoch = 2.4

[contracts.clarity-bitcoin-mini-deploy]
path = 'contracts/sBTC/clarity-bitcoin-mini-deploy.clar'
clarity_version = 2
epoch = 2.4

[contracts.clarity-bitcoin-mini]
path = 'contracts/sBTC/clarity-bitcoin-mini.clar'
clarity_version = 2
epoch = 2.4

[contracts.counter]
path = 'contracts/counter.clar'
clarity_version = 2
epoch = 2.4



[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
